---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: tayssirsdiri
    password: Tisd02468
    
    
- name: Tag and push to docker hub
  community.docker.docker_image:
     name: devops:latest
     repository: tayssirsdiri/projetcd:1.2
     push: yes
     source: local
