---

    - hosts: localhost
      gather_facts: true
      become: true
      roles:
       - { role: build }


    - hosts: localhost
      gather_facts: true
      become: true
      roles:
       - { role: build }

